version: "3"

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html

  composer:
    image: composer/composer
    command: composer install --ignore-platform-reqs
    volumes:
      - ./:/app

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./:/cache
    command: redis-server